class GlobalConstants:
        tokens=(
                "DO",
                "WHILE",
                "SWITCH",
                "CASE",
                "DEFAULT",
                "BREAK",
                "CONTINUE",
                "IF",
                "ELSE",
                "FOR",
                "RETURN",
                "STATIC",
                "GOTO",
                "SIZEOF",
                "CONST",
                "COLON",
                "COMMA",
                "DOT",
                "SEMICOLON",
                "OPRNTH",
                "CPRNTH",
                "OBRACE",
                "CBRACE",
                "OBRCKT",
                "CBRCKT",
                "INT",
                "FLOAT",
                "DOUBLE",
                "CHAR",
                "EQ",
                "GT",
                "GE",
                "LT",
                "LE",
                "NE",
                "PLUS",
                "MINUS",
                "TIMES",
                "DIV",
                "MOD",
                "UINCR",
                "UDECR",
                "SHINCR",
                "SHDECR",
                "SHTIMES",
                "SHDIV",
                "ID",
                "STRLIT",
                "CHRLIT",
                "NUMLIT",
                "FLOATLIT",
                "COMMENT",
                "NEWLINE",
        )

        reserved={
           "if" : "IF",
           "else" : "ELSE",
           "else if" : "ELSEIF",
           "while" : "WHILE",
           "do"     :"DO",
           "switch" : "SWITCH",
           "case" : "CASE",
           "int" : "INTEGER",
           "float" : "FLOAT",
           "char" : "CHARACTER",
           "double" : "DOUBLE",
           "return" : "RETURN",
        }
